# Generated by Django 5.1 on 2024-08-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kindergarten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("teacher_count", models.IntegerField()),
                ("class_count", models.IntegerField()),
                ("student_limit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("education", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("alive", models.BooleanField(default=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("has_house", models.BooleanField(default=False)),
                ("married", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=15, unique=True)),
                ("birthdate", models.DateField()),
                ("address", models.TextField()),
                ("toilet_education", models.BooleanField(default=False)),
                ("school_experience", models.BooleanField(default=False)),
                ("points", models.IntegerField(default=0)),
                (
                    "kindergarten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kindergarten_registration.kindergarten",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(to="kindergarten_registration.parent"),
                ),
            ],
        ),
    ]
