# Generated by Django 5.1 on 2024-08-28 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kres_ismi', models.CharField(max_length=100)),
                ('siniflar', models.IntegerField(default=5)),
                ('sinif_basi_ogrenci', models.IntegerField(default=10)),
                ('toplam_ogrenci_limit', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('elendi', models.BooleanField(default=False)),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(blank=True, max_length=100)),
                ('tc_no', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('adres', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('kayıt_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('tuvalet_egitimi', models.BooleanField(default=False)),
                ('okul_tecrubesi', models.CharField(blank=True, default='None', max_length=10)),
                ('devlet_ozel', models.CharField(blank=True, choices=[('Devlet', 'Devlet'), ('Özel', 'Özel')], max_length=10, null=True)),
                ('kardes_sayisi', models.IntegerField(blank=True, default=0)),
                ('anne_isim', models.CharField(blank=True, max_length=100)),
                ('anne_soyisim', models.CharField(blank=True, max_length=100)),
                ('anne_telefon', models.CharField(blank=True, max_length=20)),
                ('anne_egitim', models.CharField(blank=True, max_length=100)),
                ('anne_meslek', models.CharField(blank=True, max_length=100)),
                ('anne_kurum', models.CharField(blank=True, max_length=100)),
                ('anne_yasiyor', models.BooleanField(default=True)),
                ('anne_oz', models.BooleanField(default=True)),
                ('anne_maas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baba_isim', models.CharField(blank=True, max_length=100)),
                ('baba_soyisim', models.CharField(blank=True, max_length=100)),
                ('baba_telefon', models.CharField(blank=True, max_length=20)),
                ('baba_egitim', models.CharField(blank=True, max_length=100)),
                ('baba_meslek', models.CharField(blank=True, max_length=100)),
                ('baba_kurum', models.CharField(blank=True, max_length=100)),
                ('baba_yasiyor', models.BooleanField(default=True)),
                ('baba_oz', models.BooleanField(default=True)),
                ('baba_maas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evlimi', models.BooleanField(default=True)),
                ('ev_varmi', models.BooleanField(default=True)),
                ('kres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='kindergarten_registration.kres')),
                ('tercih_edilen_okul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_registration.kres')),
            ],
        ),
        migrations.CreateModel(
            name='Sınıf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('yas_grubu', models.IntegerField()),
                ('ilk_yari', models.BooleanField(default=True)),
                ('kres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kres_siniflar', to='kindergarten_registration.kres')),
                ('students', models.ManyToManyField(blank=True, related_name='sinif_students', to='kindergarten_registration.ogrenci')),
            ],
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sınıf_students', to='kindergarten_registration.sınıf'),
        ),
    ]
