# Generated by Django 5.1 on 2024-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="kindergarten",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parents",
        ),
        migrations.RemoveField(
            model_name="student",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="student",
            name="points",
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_education",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_house",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_marital_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_occupation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="parent1_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_education",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_house",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_marital_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_occupation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="parent2_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name="Kindergarten",
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
    ]
