# Generated by Django 5.1 on 2024-08-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0003_kindergarten_student_school_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="kindergarten",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="kindergarten_registration.kindergarten",
            ),
        ),
    ]
