# Generated by Django 5.1 on 2024-08-20 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0004_student_kindergarten"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kres_ismi", models.CharField(max_length=100)),
                ("siniflar", models.IntegerField(default=5)),
                ("sinif_basi_ogrenci", models.IntegerField(default=10)),
                ("toplam_ogrenci_limit", models.IntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="kindergarten",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="address",
            new_name="adres",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_education",
            new_name="anne_egitim",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_house",
            new_name="anne_ev_varmi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_marital_status",
            new_name="anne_evlimi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_name",
            new_name="anne_ismi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_salary",
            new_name="anne_maas",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_occupation",
            new_name="anne_meslek",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_phone",
            new_name="anne_telefon",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent1_alive",
            new_name="anne_yasiyor",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_education",
            new_name="baba_egitim",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_house",
            new_name="baba_ev_varmi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_marital_status",
            new_name="baba_evlimi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_name",
            new_name="baba_isim",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_salary",
            new_name="baba_maas",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_occupation",
            new_name="baba_meslek",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_phone",
            new_name="baba_telefon",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="parent2_alive",
            new_name="baba_yasiyor",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="isim",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="sibling_count",
            new_name="kardes_sayisi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="school_experience",
            new_name="okul_tecrubesi",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="student_id",
            new_name="tc_no",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="toilet_education",
            new_name="tuvalet_egitimi",
        ),
        migrations.RemoveField(
            model_name="student",
            name="school_type",
        ),
        migrations.AddField(
            model_name="student",
            name="devlet_ozel",
            field=models.CharField(
                blank=True,
                choices=[("Devlet", "Devlet"), ("Özel", "Özel")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="kres",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="kindergarten_registration.kres",
            ),
        ),
        migrations.DeleteModel(
            name="Kindergarten",
        ),
    ]
