# Generated by Django 5.1 on 2024-08-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0005_kres_remove_student_kindergarten_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Ogrenci",
        ),
    ]
