# Generated by Django 5.1 on 2024-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0006_rename_student_ogrenci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogrenci",
            name="okul_tecrubesi",
            field=models.CharField(
                choices=[("Yok", "Yok"), ("Devlet", "Devlet"), ("Özel", "Özel")],
                default="None",
                max_length=10,
            ),
        ),
    ]
