# Generated by Django 5.1 on 2024-08-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0007_alter_ogrenci_okul_tecrubesi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogrenci",
            name="okul_tecrubesi",
            field=models.CharField(
                choices=[
                    ("None", "No Experience"),
                    ("Devlet", "Devlet"),
                    ("Özel", "Özel"),
                ],
                default="Yok",
                max_length=10,
            ),
        ),
    ]
