# Generated by Django 5.1 on 2024-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindergarten_registration", "0008_alter_ogrenci_okul_tecrubesi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogrenci",
            name="anne_egitim",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="anne_ismi",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="anne_meslek",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="anne_telefon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="baba_egitim",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="baba_isim",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="baba_meslek",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="baba_telefon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="kardes_sayisi",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="okul_tecrubesi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "No Experience"),
                    ("Devlet", "Devlet"),
                    ("Özel", "Özel"),
                ],
                default="None",
                max_length=10,
            ),
        ),
    ]
