# Generated by Django 5.1 on 2024-08-22 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0009_alter_ogrenci_anne_egitim_alter_ogrenci_anne_ismi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='anne_kurum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='baba_kurum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='dogum_tarihi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='elendi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='kayıt_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='tercih_edilen_okul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_registration.kres'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='tc_no',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Sınıf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('yas_grubu', models.IntegerField()),
                ('ilk_yari', models.BooleanField(default=True)),
                ('kres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kres_siniflar', to='kindergarten_registration.kres')),
                ('students', models.ManyToManyField(blank=True, related_name='sinif_students', to='kindergarten_registration.ogrenci')),
            ],
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sınıf_students', to='kindergarten_registration.sınıf'),
        ),
    ]
