# Generated by Django 5.1 on 2024-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0010_ogrenci_anne_kurum_ogrenci_baba_kurum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrenci',
            old_name='anne_ismi',
            new_name='anne_isim',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='anne_ev_varmi',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='anne_evlimi',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='baba_ev_varmi',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='baba_evlimi',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='anne_oz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='anne_soyisim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='baba_oz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='baba_soyisim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='ev_varmi',
            field=models.CharField(blank=True, choices=[('Ev Sahibi', 'Ev Sahibi'), ('Kira', 'Kira')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='evlimi',
            field=models.CharField(blank=True, choices=[('Evli', 'Evli'), ('Ayrı', 'Ayrı')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='soyisim',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
