# Generated by Django 5.1 on 2024-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0011_rename_anne_ismi_ogrenci_anne_isim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='ev_varmi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='evlimi',
            field=models.BooleanField(default=True),
        ),
    ]
