# Generated by Django 5.1 on 2024-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0012_alter_ogrenci_ev_varmi_alter_ogrenci_evlimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='id',
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='tc_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
