# Generated by Django 5.1 on 2024-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0013_remove_ogrenci_id_alter_ogrenci_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='tc_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
