# Generated by Django 5.1 on 2024-08-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0014_alter_ogrenci_tc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='kreslerfk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_registration.kres'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='okul_tecrubesi',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='tercih_edilen_okul',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
