# Generated by Django 5.1 on 2024-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0015_ogrenci_kreslerfk_alter_ogrenci_okul_tecrubesi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='tercih_edilen_okul',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
