# Generated by Django 5.1 on 2024-08-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0018_alter_ogrenci_tercih_edilen_okul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='kreslerfk',
        ),
    ]
