# Generated by Django 5.1 on 2024-08-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0019_remove_ogrenci_kreslerfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='tercih_edilen_okul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten_registration.kres'),
        ),
    ]
