# Generated by Django 5.1 on 2024-08-28 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0022_alter_sınıf_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciSinif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_registration.kres')),
                ('siniffk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_registration.sınıf')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten_registration.ogrenci')),
            ],
        ),
    ]
