# Generated by Django 5.1 on 2024-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten_registration', '0026_alter_sınıf_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sınıf',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='sınıf_students', to='kindergarten_registration.ogrenci'),
        ),
    ]
